cmake_minimum_required(VERSION 3.20)

project(shell LANGUAGES C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(
    ${PROJECT_NAME}
    src/main.c
    src/shell/shell.c
)

target_include_directories(
    ${PROJECT_NAME}
    PRIVATE
    src/
)
